# Generated by Django 3.1.3 on 2022-06-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='name',
            new_name='my_name',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='posts_Main_Img',
            new_name='posts_main_img',
        ),
    ]
